# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#
# Reproduce locally by running:
# ```r
# pak::pak(c("any::pkgdown", "."), dependencies = "Config/Needs/website")
# pkgdown::build_site()
# ```
on:
  push:
    branches: [main, master]
    paths:
      - 'README.Rmd'
      - 'README.md'
      - 'index.Rmd'
      - 'index.md'
      - 'man/**'
      - 'vignettes/**'
      - '_pkgdown.yml'
      - 'pkgdown/**'
      - 'DESCRIPTION'
      - '.Rbuildignore'
      - '.github/**'
  merge_group:
  pull_request:
    paths:
      - 'README.Rmd'
      - 'README.md'
      - 'index.Rmd'
      - 'index.md'
      - 'man/**'
      - 'vignettes/**'
      - '_pkgdown.yml'
      - 'pkgdown/**'
      - 'DESCRIPTION'
      - '.Rbuildignore'
      - '.github/**'
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Check website links
        uses: untitaker/hyperlink@0.1.44
        with:
          args: docs/

      - name: Deploy to GitHub pages ðŸš€
        if: github.event_name != 'merge_group' && github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.7.4
        with:
          # We clean on releases because we want to remove old vignettes,
          # figures, etc. that have been deleted from the `main` branch.
          # But we clean ONLY on releases because we want to be able to keep
          # both the 'stable' and 'dev' websites.
          # Also discussed in https://github.com/r-lib/actions/issues/484
          clean: ${{ github.event_name == 'release' }}
          branch: gh-pages
          folder: docs
